### ISSUE TITLE
Documentation example not working for longest_prefix()

### ISSUE THREAD

**Issue by evandrocoan** [google/pygtrie#24]
The documentation shows: https://pygtrie.readthedocs.io/en/stable/#pygtrie.Trie.longest_prefix
![image](https://user-images.githubusercontent.com/5332158/49682396-7b93ee00-fa9a-11e8-96a4-a6176c686176.png)

But when I try to run the same example, it does not has a readable output:
```python
import pygtrie
trie = pygtrie.StringTrie()
trie['foo'] = 'Foo'
trie['foo/bar/baz'] = 'Baz'
print( trie.longest_prefix('foo/bar/baz/qux') )
print( trie.longest_prefix('does/not/exist') )
# -->
<pygtrie.Trie._Step object at 0x000002519E36C818>
<pygtrie.Trie._NoneStep object at 0x000002519C09D0D0>
```

**Comment by mina86** [comment]
Fixed in https://github.com/mina86/pygtrie/commit/8ce5ea1c4475f42a621bf7ac359ccb94e50de49c.

Another issue was that ReadTheDocs was misconfigured so documentation for version 2.3 wasn’t built. This has been fixed as well.

The root cause was that in 2.3, `longest_prefix` and `shortest_prefix` changed from returning a tuple to returning a `_Step` or a `_NoneStep` object which didn’t have a `__repr__` method. The object supports indexing so the documentation wasn’t completely misleading; just a little bit.

**Comment by evandrocoan** [comment]
Thanks for fixing it so fast!
